### ISSUE TITLE
stopthecap - Positions are not being liquidated when they should

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#10]
stopthecap

high

# Positions are not being liquidated when they should

## Summary
Positions are not being liquidated when they should

## Vulnerability Detail
Positions are being liquidated in the `liquidate` function:
https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346-L374

as you can see, the position can only be liquidated if it is not liquidable:
https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L487

The problem is that the total `total_debt_shares[_debt_token]` is not updated when checking whether the positon is liquidable neither when calling `liquidate`  You can see on the following links the progression of the function calls to calculate whether a position is liquidable or not:
 
https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L444

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1142

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1099

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1111

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1117C16-L1117C16

As seen, `total_debt_shares[_debt_token]` is not updated to the current `total_debt_shares[_debt_token]` by calling `_update_debt` and therefore a stale `total_debt_shares[_debt_token]` is used to calculate whether a position is liquidable. Not accounting for positions that are in fact liquidable because the debt is not yet updated.

## Impact
Not updating the debt before liquidating a position will cause that positions that are in fact below the liquidation threshold, not be liquidated until debt is updated

## Code Snippet
https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346-L374

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1117C16-L1117C16
## Tool used

Manual Review

## Recommendation
Call `_update_debt` at the beginning of the `liquidate` function

**Comment by fatherGoose1** [comment]
Escalate

This is invalid. Even though `_update_debt()` is not called, the pending debt is accounted for in the view functions. The view functions are a cascade of view functions, so it must be followed to the very end:

`_is_liquidateable()` -> `_effective_leverage()` -> `_debt()` -> `_debt_shares_to_amount()` -> `_amount_per_debt_share()` -> `_total_debt_plus_pending_interest()` -> `_debt_interest_since_last_update()` -> Correctly accounts for the accrued debt.

```solidity
def _amount_per_debt_share(_debt_token: address) -> uint256:
    # @dev returns extra 18 decimals for precision!
    return (
        self._total_debt_plus_pending_interest(_debt_token)
        * PRECISION
        * PRECISION
        / self.total_debt_shares[_debt_token]
    )
```

```solidity
def _total_debt_plus_pending_interest(_debt_token: address) -> uint256:
    return self.total_debt_amount[_debt_token] + self._debt_interest_since_last_update(
        _debt_token
    )
```

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is invalid. Even though `_update_debt()` is not called, the pending debt is accounted for in the view functions. The view functions are a cascade of view functions, so it must be followed to the very end:
> 
> `_is_liquidateable()` -> `_effective_leverage()` -> `_debt()` -> `_debt_shares_to_amount()` -> `_amount_per_debt_share()` -> `_total_debt_plus_pending_interest()` -> `_debt_interest_since_last_update()` -> Correctly accounts for the accrued debt.
> 
> ```solidity
> def _amount_per_debt_share(_debt_token: address) -> uint256:
>     # @dev returns extra 18 decimals for precision!
>     return (
>         self._total_debt_plus_pending_interest(_debt_token)
>         * PRECISION
>         * PRECISION
>         / self.total_debt_shares[_debt_token]
>     )
> ```
> 
> ```solidity
> def _total_debt_plus_pending_interest(_debt_token: address) -> uint256:
>     return self.total_debt_amount[_debt_token] + self._debt_interest_since_last_update(
>         _debt_token
>     )
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Recommendation: 
change the original judging, to invalid.

> Escalate
> 
> This is invalid. Even though `_update_debt()` is not called, the pending debt is accounted for in the view functions. The view functions are a cascade of view functions, so it must be followed to the very end:
> 
> `_is_liquidateable()` -> `_effective_leverage()` -> `_debt()` -> `_debt_shares_to_amount()` -> `_amount_per_debt_share()` -> `_total_debt_plus_pending_interest()` -> `_debt_interest_since_last_update()` -> Correctly accounts for the accrued debt.
> 
> ```solidity
> def _amount_per_debt_share(_debt_token: address) -> uint256:
>     # @dev returns extra 18 decimals for precision!
>     return (
>         self._total_debt_plus_pending_interest(_debt_token)
>         * PRECISION
>         * PRECISION
>         / self.total_debt_shares[_debt_token]
>     )
> ```
> 
> ```solidity
> def _total_debt_plus_pending_interest(_debt_token: address) -> uint256:
>     return self.total_debt_amount[_debt_token] + self._debt_interest_since_last_update(
>         _debt_token
>     )
> ```

The chained view functions did take into account the accrued interest, and the `debt_amount` is also derived from `_debt()`, including the accrued interest. The function is working as expected, no loss.

So this one should be invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Has duplicates
Agree with the Escalation. This is a non issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [fatherGoose1](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/10/#issuecomment-1646075509): accepted
