### ISSUE TITLE
stopthecap - Hardcoded slippage will make orders to be stuck in specific market conditions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#19]
stopthecap

high

# Hardcoded slippage will make orders to be stuck in specific market conditions

## Summary
Hardcoded slippage will make orders to be stuck in specific market conditions

## Vulnerability Detail
Currently the calculation of the slippage for swapping, uses a constant named `liquidate_slippage` , which is a value choosen by the owner. This slippage will be used for the calculation in every swap that needs of unstoppables's calculation, in any market condition. Therefore, it is the same to say that the slippage is calculated using a hardcoded parameter.

https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L426

It does not just on limit orders, also in spot orders, where it is specified the variable `MAX_SLIPPAGE` has the value to calculate the `min_amount_out` for swapping when executing `dca` orders
## Code Snippet
https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L426
## Tool used

Manual Review

## Recommendation
Use the uniswap helper library to calculate slippage instead of hardcoding it

**Comment by 0xffff11** [comment]
Escalate

This is a bug in the code that was introduced when trying to prevent a killing slippage for the user. This approach is wrong and it impacts the users funds. Your reasoning is why this is should be a medium and not a high

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a bug in the code that was introduced when trying to prevent a killing slippage for the user. This approach is wrong and it impacts the users funds. Your reasoning is why this is should be a medium and not a high

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by twicek** [comment]
Escalate for 10 USDC
This should be invalid.
The admin can modifiy the slippage protection according to market conditions using `set_liquidate_slippage_for_market`.
Lead Judge's comment shows why this is also invalid for the spot dex.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> This should be invalid.
> The admin can modifiy the slippage protection according to market conditions using `set_liquidate_slippage_for_market`.
> Lead Judge's comment shows why this is also invalid for the spot dex.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.

> Escalate
> 
> This is a bug in the code that was introduced when trying to prevent a killing slippage for the user. This approach is wrong and it impacts the users funds. Your reasoning is why this is should be a medium and not a high

Whether to provide this parameter is user's input choice. Providing nothing means user accepts the system's default slippage value.

User's loss due to their own input is low/informaional.

**Comment by 141345** [comment]
> Escalate for 10 USDC This should be invalid. The admin can modifiy the slippage protection according to market conditions using `set_liquidate_slippage_for_market`. Lead Judge's comment shows why this is also invalid for the spot dex.

same as above

**Comment by 0xffff11** [comment]
I want to reference 2 points to why I think this issue is valid. 

Point 1: `The admin can modifiy the slippage protection according to market conditions using set_liquidate_slippage_for_market.`  It will still be "hardcoded". Admin is not changing the slippage in every transaction. It is impossible to predict what the slippage will be in the following blocks, so even if they update it once in a while, the value will be incorrect

Point2:  `Whether to provide this parameter is user's input choice.`  Normal users/integrations/devs or anyone interacting with unstoppable expect the contracts/function to work as intended and correctly. If unstoppable as a feature to calculate slippage depending on what the user inputs and it calculates this slippage wrong, then it is on unstoppable's side, not the user. Imagine going to uniswap and depending on the amount you pass it calculates the slippage in x  or y way, but y is wrong.

I strongly believe that for the given points this should be valid. I think medium is more accurate than high also.

**Comment by 141345** [comment]
> Point2: `Whether to provide this parameter is user's input choice.` Normal users/integrations/devs or anyone interacting with unstoppable expect the contracts/function to work as intended and correctly. If unstoppable as a feature to calculate slippage depending on what the user inputs and it calculates this slippage wrong, then it is on unstoppable's side, not the user. Imagine going to uniswap and depending on the amount you pass it calculates the slippage in x or y way, but y is wrong.

The users can always provide the parameter if they don't feel comfortable with the system's slippage formula. 

The `MAX_SLIPPAGE` is a default value, in case users do not provide one. Better than nothing.
A more sophicicated model or formula for slippage calculation could be a design improvement.

**Comment by 0xffff11** [comment]
> > Point2: `Whether to provide this parameter is user's input choice.` Normal users/integrations/devs or anyone interacting with unstoppable expect the contracts/function to work as intended and correctly. If unstoppable as a feature to calculate slippage depending on what the user inputs and it calculates this slippage wrong, then it is on unstoppable's side, not the user. Imagine going to uniswap and depending on the amount you pass it calculates the slippage in x or y way, but y is wrong.
> 
> The users can always provide the parameter if they don't feel comfortable with the system's slippage formula.
> 
> The `MAX_SLIPPAGE` is a default value, in case users do not provide one. Better than nothing. A more sophicicated model or formula for slippage calculation could be a design improvement.

The user shouldn't be or not be comfortable with the system's formula because the user should not know or even has to understand the code and know that the calculation is wrong. You are saying `A more sophisticated model or formula for slippage calculation could be a design improvement.`  If the current formula causes the slippage to be incorrect and affects the funds, that is not a design decision, that is a vulnerability

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the second escalation and that this is not an issue. Additional sponsor comment:
> Yeah, disagree with this  being an issue. User has the option to give manual input and we default to sensible value for the given market otherwise.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [twicek](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/19/#issuecomment-1644122001): accepted
- [0xffff11](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/19/#issuecomment-1642763061): rejected
