### ISSUE TITLE
BugHunter101 - `execute_dca_order()` does not check if `order.account == msg.sender`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#7]
BugHunter101

medium

# `execute_dca_order()` does not check if `order.account == msg.sender`

## Summary

`execute_dca_order()` does not check if `order.account == msg.sender` , it may cause attacker to cancel dca_order and clear dca_order when the user is temporarily not eligible for execution

## Vulnerability Detail

As we can see, in `execute_dca_order()`, it will check `account_balance < order.amount_in_per_execution`,and the `account_balance = ERC20(order.token_in).balanceOf(order.account)`. However, if `iaccount_balance < order.amount_in_per_execution` ,it will call `_cancel_dca_order()`, then, the attacker can use call execute_dca_order() to clear someone 's order when atttacker monitor the user's`ERC20(order.token_in).balanceOf(order.account)` < `order.amount_in_per_execution`
```vyper
    # ensure user has enough token_in
    account_balance: uint256 = ERC20(order.token_in).balanceOf(order.account)
    if account_balance < order.amount_in_per_execution:
        log DcaOrderFailed(_uid, order.account, "insufficient balance")
        self._cancel_dca_order(_uid, "insufficient balance")#@audit
        return
```
For example:
1. Alice set a order and order.amount_in_per_execution = 100 tokenA, and now Alice have 101 tokenA
2. But now, Alice may need to use 50 tokenA to do other things, and may return later
3. Bob monitor the Alice tokenA 's balance is change to 101-50 =51 ,so this conform to`ERC20(order.token_in).balanceOf(order.account)` < `order.amount_in_per_execution`
4. Bob call `execute_dca_order()` and set the `_uid` is Alice 
5. Because of `ERC20(order.token_in).balanceOf(order.account)` < `order.amount_in_per_execution` ,so the order will clear
6. Now Alice got back 50 tokenA, and the balance is 101, it will cause wrong when she wants to call `execute_dca_order()` because of the order is clear.

## Impact

it may cause attacker to cancel dca_order and clear dca_order when the user is temporarily not eligible for execution

## Code Snippet

https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/spot-dex/Dca.vy#L190

## Tool used

Manual Review

## Recommendation

Check if `order.account == msg.sender` . And please check other function like `exec_xxx_order()`, it maybe has same problem.

**Comment by Dlangman** [comment]
Escalate for 10 USDC
I think the problem risk is there rather than `Excluded`

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> I think the problem risk is there rather than `Excluded`

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.

> Escalate for 10 USDC 
> I think the problem risk is there rather than `Excluded`

msg.sender is the keeper, not the order.account.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Lead judge, don't see a valid issue here

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Dlangman](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/7/#issuecomment-1643019741): rejected
