### ISSUE TITLE
GimelSec - `Univ3Twap.sqrtPriceX96ToUint` could suffer from overflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#90]
GimelSec

medium

# `Univ3Twap.sqrtPriceX96ToUint` could suffer from overflow

## Summary

`Univ3Twap.sqrtPriceX96ToUint` should be aware of the overflow of `uint256(sqrtPriceX96) * uint256(sqrtPriceX96)`.

## Vulnerability Detail

The calculation in `sqrtPriceX96ToUint` is correct. But it doesn’t handle the potential overflow of  `uint256(sqrtPriceX96) * uint256(sqrtPriceX96)` if `uint256(sqrtPriceX96) > type(uint128).max` .
https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/utils/Univ3Twap.sol#L46
```solidity
    function sqrtPriceX96ToUint(uint160 sqrtPriceX96, uint8 decimalsToken0)
        public
        pure
        returns (uint256)
    {
        uint256 numerator1 = uint256(sqrtPriceX96) * uint256(sqrtPriceX96);
        uint256 numerator2 = 10**decimalsToken0;
        return FullMath.mulDiv(numerator1, numerator2, 1 << 192);
    }
```

The library in Uniswap has the correct implementation that can prevent overflow.
https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/OracleLibrary.sol#L57
```solidity
    function getQuoteAtTick(
        int24 tick,
        uint128 baseAmount,
        address baseToken,
        address quoteToken
    ) internal pure returns (uint256 quoteAmount) {
        uint160 sqrtRatioX96 = TickMath.getSqrtRatioAtTick(tick);

        // Calculate quoteAmount with better precision if it doesn't overflow when multiplied by itself
        if (sqrtRatioX96 <= type(uint128).max) {
            uint256 ratioX192 = uint256(sqrtRatioX96) * sqrtRatioX96;
            quoteAmount = baseToken < quoteToken
                ? FullMath.mulDiv(ratioX192, baseAmount, 1 << 192)
                : FullMath.mulDiv(1 << 192, baseAmount, ratioX192);
        } else {
            uint256 ratioX128 = FullMath.mulDiv(sqrtRatioX96, sqrtRatioX96, 1 << 64);
            quoteAmount = baseToken < quoteToken
                ? FullMath.mulDiv(ratioX128, baseAmount, 1 << 128)
                : FullMath.mulDiv(1 << 128, baseAmount, ratioX128);
        }
    }
```

## Impact

`Univ3Twap.sqrtPriceX96ToUint` may overflow. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/utils/Univ3Twap.sol#L46

## Tool used

Manual Review

## Recommendation

Reference the implementation of UniSwap library
https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/OracleLibrary.sol#L57

**Comment by 0xbepresent** [comment]
Escalate

There are not realistic scenarios where `sqrtPriceX96` could be greater than `2**128`. This issue could be low/informational. More information in the nex discussion https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/34

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> There are not realistic scenarios where `sqrtPriceX96` could be greater than `2**128`. This issue could be low/informational. More information in the nex discussion https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/34

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by shealtielanz** [comment]
Go and do your research, there are scenarios where `sqrtPriceX96` can be greater than zero, and that's why Uniswap ensured to prevent this issue.
Based on sherlock guidelines, this can cause issues in the future if this happens thereby making this Issue  a Valid Medium.
Same Issue has been submitted by the likes of Trust

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.

> Escalate
> 
> There are not realistic scenarios where `sqrtPriceX96` could be greater than `2**128`. This issue could be low/informational. More information in the nex discussion [sherlock-audit/2023-06-arrakis-judging#34](https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/34)

Based on the numbers given in the link, there could be situations sqrtPriceX96 reaching the limit. No popular main stream token pair today does not mean never in the future.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this issue as a valid low based on the current impact as there is no pool that exists currently and unlikely that it does, the impact of revert can together be counted as low.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xbepresent](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/90/#issuecomment-1644510286): accepted

**Comment by shealtielanz** [comment]
I don't agree
