### ISSUE TITLE
GimelSec - The calculation of `twap` in `Univ3Twap.getTwap` could overflow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#91]
GimelSec

medium

# The calculation of `twap` in `Univ3Twap.getTwap` could overflow

## Summary

`Univ3Twap.getTwap` calculates the `twap` by multiplying all the individual twaps of the pools and then dividing it by 10**decimals. However, it's important to be aware that an overflow could occur when performing the multiplication of the twaps.

## Vulnerability Detail

`Univ3Twap.getTwap` calculates the `twap` by multiplying all the individual twaps of the pools and then dividing it by 10**decimals.
https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/utils/Univ3Twap.sol#L74
```solidity
    function getTwap(address[] calldata path, uint24[] calldata fees, uint32 twapLength) public view returns(uint256) {
        …

        uint256 twap = 1;
        uint256 decimals = 0;

        for(uint i = 0; i < path.length-1; i++) {
            uint256 t = getSingleHopTwap(path[i], path[i+1], fees[i], twapLength);
            twap = twap * t; // @audit: overflow could occur.
            decimals += IERC20(path[i+1]).decimals();
        }

        return twap * 10**IERC20(path[path.length-1]).decimals() / 10**decimals;
    }
```

## Impact

`Univ3Twap.getTwap` may suffer from overflow. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/utils/Univ3Twap.sol#L74

## Tool used

Manual Review

## Recommendation

Modify the implementation to mitigate overflow:
```diff
    function getTwap(address[] calldata path, uint24[] calldata fees, uint32 twapLength) public view returns(uint256) {
        …

        uint256 twap = 1;
-       uint256 decimals = 0;
+       uint256 prevDecimals = 1;

        for(uint i = 0; i < path.length-1; i++) {
            uint256 t = getSingleHopTwap(path[i], path[i+1], fees[i], twapLength);
-           twap = twap * t;
+           twap = twap * t / prevDecimals;
-           decimals += IERC20(path[i+1]).decimals();
        }

-       return twap * 10**IERC20(path[path.length-1]).decimals() / 10**decimals;
+       return twap;
    }

```

**Comment by twicek** [comment]
Escalate for 10 USDC
This report is a duplicate of #90.
The only way `twap = twap * t;` would revert in the loop is if it already reverted in the `getSingleHopTwap` function like in #90. In the loop, `getSingleHopTwap` is called at most twice (3 tokens) and the only way it would revert is if `twap * t` was bigger than uint.max which would only happen if one of both of `getSingleHopTwap` would already revert.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> This report is a duplicate of #90.
> The only way `twap = twap * t;` would revert in the loop is if it already reverted in the `getSingleHopTwap` function like in #90. In the loop, `getSingleHopTwap` is called at most twice (3 tokens) and the only way it would revert is if `twap * t` was bigger than uint.max which would only happen if one of both of `getSingleHopTwap` would already revert.  
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xDE-GEN** [comment]
The product of 3 token's twap should be greater than uint256.max, which is hard to judge as medium risk? 
I think it's valid low.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.

> Escalate for 10 USDC This report is a duplicate of #90. The only way `twap = twap * t;` would revert in the loop is if it already reverted in the `getSingleHopTwap` function like in #90. In the loop, `getSingleHopTwap` is called at most twice (3 tokens) and the only way it would revert is if `twap * t` was bigger than uint.max which would only happen if one of both of `getSingleHopTwap` would already revert.

`getSingleHopTwap()` could potentially return more than uint128.max (depends on the relative price of token1/token2). The return variable of `getSingleHopTwap()` is uint256.

Based on the above potential edge case, this issue is still valid.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agreed with above comments. Given how unlikely the such pools to exists, don't see the impact of this revert as a valid medium

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [twicek](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/91/#issuecomment-1642917400): accepted
